const express = require('express');
const bodyparser = require('body-parser');
const cors = require('cors');
const feed = require('./Routes/feed');
const app = express();
app.use(cors());
app.use(bodyparser.urlencoded({ extended :  true}));
app.use(bodyparser.json());
app.use('/feed', feed);
module.exports = app;